practice1 : practice1.o matrix_chain_order.o
	g++ -o practice1 practice1.o matrix_chain_order.o

practice1.o : practice1.cc matrix_chain_order.hh
	g++ -c practice1.cc

matrix_chain_order.o : matrix_chain_order.cc matrix_chain_order.hh
	g++ -c matrix_chain_order.cc


